In [1]:
import numpy as np

In [2]:
x = [[31,23,12,14,56],[34,65,64,21,24],[98,76,90,17,28]]

In [3]:
x

[[31, 23, 12, 14, 56], [34, 65, 64, 21, 24], [98, 76, 90, 17, 28]]

In [5]:
y = np.array(x)


In [30]:
y

array([[31, 23, 12, 14, 56],
       [34, 65, 64, 21, 24],
       [98, 76, 90, 17, 28]])

In [31]:
y.max()

98

In [32]:
y.min()

12

In [37]:
y.argmax()

10

In [38]:
y.argmin()

2

In [34]:
np.random.rand(9) #//randn for negative

array([0.5814778 , 0.94275326, 0.20680338, 0.58344134, 0.06232386,
       0.79616762, 0.55406068, 0.42443268, 0.91125913])

In [36]:
np.random.randint(100)

49

y.min()

In [15]:
np.zeros((2,3)) + 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [43]:
z = np.arange(22)

In [44]:
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [53]:
n = z[3:10] = 23

In [56]:
n

23

In [58]:
z

array([ 0,  1,  2, 23, 23, 23, 23, 23, 23, 23, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [60]:
n = z.copy()

In [62]:
n

array([ 0,  1,  2, 23, 23, 23, 23, 23, 23, 23, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [67]:
p = np.arange(25).reshape(5,5)

In [70]:
p[4,3]

23

In [72]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
p[0:4,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [76]:
p>12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [77]:
p[p>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [79]:
p[p%4]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [ 0,  1,  2,  3,  4]]])

In [80]:
z[z%4]

array([ 0,  1,  2, 23, 23, 23, 23, 23, 23, 23,  2, 23,  0,  1,  2, 23,  0,
        1,  2, 23,  0,  1])

In [81]:
z

array([ 0,  1,  2, 23, 23, 23, 23, 23, 23, 23, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [82]:
r = np.arange(10,25)

In [83]:
r


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [84]:
s = np.arange(2,17)

In [85]:
s

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [86]:
m = r + s  # we can perform same like *,/,%,- etc

In [87]:
m

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [88]:
np.sin(s)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
       -0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332])

In [89]:
np.log(r)

array([2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [98]:
o = np.arange(10,25).reshape(3,5)

In [99]:
o

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [100]:
q = np.arange(2,17).reshape(3,5)

In [101]:
q

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [102]:
o + q  # we can perform same like *,/,%,- etc

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [105]:
h = np.full((3,3),True)

In [106]:
h

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [116]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

x = arr[arr%2 == 1] = -1

print(x)

-1


In [121]:
np.intersect1d(o,q)

array([10, 11, 12, 13, 14, 15, 16])